export const responseMeal = {
  idMeal: "52839",
  strMeal: "Chilli prawn linguine",
  strDrinkAlternate: null,
  strCategory: "Pasta",
  strArea: "Italian",
  strInstructions:
    "Mix the dressing ingredients in a small bowl and season with salt and pepper. Set aside.\r\n\r\nCook the pasta according to the packet instructions. Add the sugar snap peas for the last minute or so of cooking time.\r\n\r\nMeanwhile, heat the oil in a wok or large frying pan, toss in the garlic and chilli and cook over a fairly gentle heat for about 30 seconds without letting the garlic brown. Tip in the prawns and cook over a high heat, stirring frequently, for about 3 minutes until they turn pink.\r\n\r\nAdd the tomatoes and cook, stirring occasionally, for 3 minutes until they just start to soften. Drain the pasta and sugar snaps well, then toss into the prawn mixture. Tear in the basil leaves, stir, and season with salt and pepper.\r\n\r\nServe with salad leaves drizzled with the lime dressing, and warm crusty bread.",
  strMealThumb:
    "https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg",
  strTags: null,
  strYoutube: "https://www.youtube.com/watch?v=SC17Mc70Db0",
  strIngredient1: "Linguine Pasta",
  strIngredient2: "Sugar Snap Peas",
  strIngredient3: "Olive Oil",
  strIngredient4: "Garlic Clove",
  strIngredient5: "Red Chilli",
  strIngredient6: "King Prawns",
  strIngredient7: "Cherry Tomatoes",
  strIngredient8: "Basil Leaves",
  strIngredient9: "Lettuce",
  strIngredient10: "Bread",
  strIngredient11: "Fromage Frais",
  strIngredient12: "Lime",
  strIngredient13: "Caster Sugar",
  strIngredient14: "",
  strIngredient15: "",
  strIngredient16: "",
  strIngredient17: "",
  strIngredient18: "",
  strIngredient19: "",
  strIngredient20: "",
  strMeasure1: "280g",
  strMeasure2: "200g",
  strMeasure3: "2 tblsp ",
  strMeasure4: "2 cloves chopped",
  strMeasure5: "1 large",
  strMeasure6: "24 Skinned",
  strMeasure7: "12",
  strMeasure8: "Handful",
  strMeasure9: "Leaves",
  strMeasure10: "to serve",
  strMeasure11: "2 tbsp",
  strMeasure12: "Grated Zest of 2",
  strMeasure13: "2 tsp",
  strMeasure14: "",
  strMeasure15: "",
  strMeasure16: "",
  strMeasure17: "",
  strMeasure18: "",
  strMeasure19: "",
  strMeasure20: "",
  strSource: "https://www.bbcgoodfood.com/recipes/1269/chilli-prawn-linguine",
  strImageSource: null,
  strCreativeCommonsConfirmed: null,
  dateModified: null,
};

export const responseDrink = {
  idDrink: "15567",
  strDrink: "Adam Sunrise",
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: "Ordinary Drink",
  strIBA: null,
  strAlcoholic: "Alcoholic",
  strGlass: "Collins Glass",
  strInstructions:
    "Fill blender up with ice. Fill half with Bartons Vodka. Put 10 tsp of sugar, add 1/2 can lemonade concentrate, fill to top with water. Blend for 60 seconds.",
  strInstructionsES:
    "Llene la licuadora con hielo. Llene la mitad con vodka Bartons. Ponga 10 cucharaditas de azúcar, añada 1/2 lata de concentrado de limonada y llene hasta arriba con agua. Licuar durante 60 segundos.",
  strInstructionsDE:
    "Den Mixer mit Eis auffüllen. Füllen Sie die Hälfte mit Bartons Wodka. 10 Teelöffel Zucker hinzufügen, 1/2 Dose Limonadenkonzentrat hinzufügen, mit Wasser füllen. 60 Sekunden lang mischen.",
  strInstructionsFR:
    "Remplir le mixeur de glace. Remplir la moitié avec de la vodka Bartons. Mettre 10 cuillères à café de sucre, ajouter 1/2 boîte de limonade concentrée et compléter avec de l'eau. Mixer pendant 60 secondes.",
  strInstructionsIT:
    "Riempi il frullatore di ghiaccio.\r\nRiempi metà con Bartons Vodka.\r\nMettere 10 cucchiaini di zucchero, aggiungere 1/2 lattina di concentrato di limonata, riempire con acqua.\r\nFrulla per 60 secondi.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  strDrinkThumb:
    "https://www.thecocktaildb.com/images/media/drink/vtuyvu1472812112.jpg",
  strIngredient1: "Vodka",
  strIngredient2: "Lemonade",
  strIngredient3: "Water",
  strIngredient4: "Sugar",
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: "1/2 ",
  strMeasure2: "1/2 can ",
  strMeasure3: "1/2 ",
  strMeasure4: "10 tsp ",
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: "No",
  dateModified: "2016-09-02 11:28:32",
};

export const connectors = [
  "the",
  "a",
  "an",
  "and",
  "with",
  "in",
  "on",
  "for",
  "of",
  "from",
  "by",
  "over",
  // "under",
  // "alongside",
];
